services:
  - type: web
    name: shinigami.X-gpt
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        value: 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   # 🔁 Replace with your actual key
      
